//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyDocument()
        {
            this.CompanyDocumentConfigurableValues = new HashSet<CompanyDocumentConfigurableValue>();
        }
    
        public int Id { get; set; }
        public string DocumentName { get; set; }
        public byte[] DocumentPath { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string DocumentType { get; set; }
        public Nullable<int> CompanyDocumentsTypeId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyDocumentConfigurableValue> CompanyDocumentConfigurableValues { get; set; }
        public virtual CompanyDocumentsType CompanyDocumentsType { get; set; }
    }
}
