//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDocumentConfigurableValue
    {
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string FieldName { get; set; }
        public string ValueType { get; set; }
        public string FieldValue { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> CompanyDocumentId { get; set; }
        public string FieldFormat { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CompanyDocument CompanyDocument { get; set; }
    }
}
