//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.CompanyDocumentConfigurableValues = new HashSet<CompanyDocumentConfigurableValue>();
            this.CompanyDocuments = new HashSet<CompanyDocument>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ManagerId { get; set; }
        public string ManagerName { get; set; }
        public string ManagerMobile { get; set; }
        public string ManagerOfficialEmail { get; set; }
        public string HRId { get; set; }
        public string HRName { get; set; }
        public string HRMobile { get; set; }
        public string HROfficialEmail { get; set; }
        public string LeadId { get; set; }
        public string LeadName { get; set; }
        public string LeadMobile { get; set; }
        public string LeadOfficialEmail { get; set; }
        public byte[] CompanyLogo { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyOfficialEmail { get; set; }
        public string CompanyOfficialContact { get; set; }
        public string CompanyWebsite { get; set; }
        public string CompanyFounder { get; set; }
        public string CompanyFoundedMonthYear { get; set; }
        public string CompanyEmployeeStrength { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyDocumentConfigurableValue> CompanyDocumentConfigurableValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyDocument> CompanyDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
