//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string FullName { get; set; }
        public byte[] Photo { get; set; }
        public string PermanentAddress { get; set; }
        public string CurrentAddress { get; set; }
        public string PAN { get; set; }
        public string Mobile { get; set; }
        public string AlternateMobile { get; set; }
        public string EmailId { get; set; }
        public string AlternateEmailId { get; set; }
        public string BloodGroup { get; set; }
        public string HighestQualification { get; set; }
        public string HighestQualificationPassoutMonthYear { get; set; }
        public string Technology { get; set; }
        public Nullable<System.DateTime> OfferDate { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string OfferDesignation { get; set; }
        public string CurrentDesignation { get; set; }
        public Nullable<decimal> OfferSalary { get; set; }
        public Nullable<decimal> CurrentSalary { get; set; }
        public string LastHikeMonthYear { get; set; }
        public Nullable<System.DateTime> ResignationDate { get; set; }
        public Nullable<System.DateTime> RelivingDate { get; set; }
        public string OfficialEmployeeId { get; set; }
        public string OfficialEmailId { get; set; }
        public string OfficialEmailIdPassword { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Adhaar { get; set; }
        public string UAN { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Company Company { get; set; }
    }
}
