//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeIncrement
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string HikeMonthYear { get; set; }
        public Nullable<int> HikeInPercentage { get; set; }
        public Nullable<decimal> HikeAmount { get; set; }
        public Nullable<decimal> SalaryAfterHike { get; set; }
        public Nullable<System.DateTime> SalaryEffectiveFrom { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
