//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEducation
    {
        public int EducationId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> EducationTypeId { get; set; }
        public string CollegeName { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<int> PassoutYear { get; set; }
        public string Specialization { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual EmployeeEducationType EmployeeEducationType { get; set; }
    }
}
