//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeManagementDBContext : DbContext
    {
        public EmployeeManagementDBContext()
            : base("name=EmployeeManagementDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyDocumentConfigurableValue> CompanyDocumentConfigurableValues { get; set; }
        public virtual DbSet<CompanyDocument> CompanyDocuments { get; set; }
        public virtual DbSet<CompanyDocumentsType> CompanyDocumentsTypes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeBankAccount> EmployeeBankAccounts { get; set; }
        public virtual DbSet<EmployeeEducation> EmployeeEducations { get; set; }
        public virtual DbSet<EmployeeEducationType> EmployeeEducationTypes { get; set; }
        public virtual DbSet<EmployeeExperiece> EmployeeExperieces { get; set; }
        public virtual DbSet<EmployeeIncrement> EmployeeIncrements { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<EmployeeITExperience> EmployeeITExperiences { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
